### ISSUE TITLE
ReactorKit with nib files

### ISSUE THREAD

**Issue by SumeraMartin** [ReactorKit/ReactorKit#11]
All examples do not use neither storyboard nor nib files. How should I resolve situation when I want use nib files for viewcontrollers? When I do it now, app crashes because IBOutlets are not initialized yet and I need access them in bind method. 

I want to do something like this, but self.collectionView is nil:

```
reactor.state
            .asObservable()
            .map { [CategorySectionModel(model: Void(), items: $0.categories)] }
            .bind(to: self.collectionView.rx.items(dataSource: self.dataSource))
            .addDisposableTo(self.disposeBag)
```

**Comment by devxoul** [comment]
`bind()` is performed when the `self.reactor` is changed. I think you can assign `self.reactor` after the `viewDidLoad()`.

**Comment by SumeraMartin** [comment]
Thanks, It worked
