### ISSUE TITLE
Add Travis build and release for Carthage

### ISSUE THREAD

**Issue by appoulsen** [ReactorKit/ReactorKit#12]
I suggest adding a Travis CI to test and build a release for Carthage

**Comment by devxoul** [comment]
@appoulsen, thanks for reporting! I'm currently writing tests. I think it'll be done in this week :)

**Comment by devxoul** [comment]
ReactorKit supports prebuilt framework from https://github.com/ReactorKit/ReactorKit/releases/tag/0.4.5 :tada:
