### ISSUE TITLE
Complex observable

### ISSUE THREAD

**Issue by SumeraMartin** [ReactorKit/ReactorKit#13]
Hi,

how would you solve problem when with one action you want to create a observable and with another action you want to do something with this already created observable?

For example, I have a observable which will emit Mutation after 10 seconds:
```
switch action {
    case .start:
        return Observable<Int>.interval(10, scheduler: MainScheduler.instance)
            .map { _ in .doSomething }
```
and now I wanna dispose or restart this observable.
```
switch action {
    case .stop:
        // What to do now?
```
How would you do that?

**Comment by devxoul** [comment]
@SumeraMartin, thanks for great question! This may be similar with https://github.com/ReactorKit/ReactorKit/issues/10#issuecomment-296396082 but there's no current solution at this time. However I'm currently working on it and will be available soon. After that, you'll be able to dispose the observable as similar as following:

```swift
switch action {
  case .start:
    return Observable<Int>.interval(10, scheduler: MainScheduler.instance)
      .map { _ in .doSomething }
      .takeUntil(self.action.filter(.stop))
```

**Comment by devxoul** [comment]
@SumeraMartin, I just realeased [ReactorKit 0.3.0](https://github.com/ReactorKit/ReactorKit/releases/tag/0.3.0) which support canceling the observables :)

**Comment by SumeraMartin** [comment]
Wow, thanks 👍
