### ISSUE TITLE
can you provide the transform methods example.

### ISSUE THREAD

**Issue by tospery** [ReactorKit/ReactorKit#132]
for ex.
func transform(action: Observable<Action>) -> Observable<Action>
func transform(state: Observable<State>) -> Observable<State>
i don't known how to use, thanks

**Comment by vkcldhkd** [comment]
Drrrible is a very good example :)

https://github.com/devxoul/Drrrible/blob/a8f6118571f66ac231dd4fda16d0995aade57a56/Drrrible/Sources/Views/ShotViewReactionButtonViewReactor.swift
