### ISSUE TITLE
How to handle Error from server

### ISSUE THREAD

**Issue by tospery** [ReactorKit/ReactorKit#137]
i don't known how to use catchError to set error in State

**Comment by tospery** [comment]
case .load:
            guard !self.currentState.isLoading else {
                return .empty()
            }
            return .concat([
                .just(.setLoading(true)),
                self.provider.kujiaService.helpInfo().catchError({ error -> Observable<HelpInfo> in
                    // self.currentState.error = error as? NSError
                    return .empty()
                }).map(Mutation.setInfo),
                .just(.setLoading(false))
            ])

**Comment by asapo** [comment]
If you need to mutate reactor's state, you just need to use `Mutation`.

```swift
enum Mutation {
    case setError(Error)
}

struct State {
    var error: Error?
}

func mutate(action: Action) -> Observable<Mutation> {
    switch action {
    case .load:
        guard !self.currentState.isLoading else {
            return .empty()
        }
        return .concat([
            .just(.setLoading(true)),
            self.provider.kujiaService.helpInfo().catchError({ error -> Observable<HelpInfo> in
                return Mutation.error(error) // Here
            }).map(Mutation.setInfo),
            .just(.setLoading(false))
        ])
    }
}

func reduce(state: State, mutation: Mutation) -> State {
  var state = state
  switch mutation {
  case let .setError(error):
    state.error = error
  }
  return state
}
```

**Comment by tospery** [comment]
> ```swift
> return Mutation.error(error)
> ```
Can't return Mutation.error(error), will compile error

**Comment by szoszig** [comment]
Call Mutation.setError(error) instead

**Comment by tospery** [comment]
> Call Mutation.setError(error) instead

after call Mutation.setError(error), the reduce method never called

**Comment by asapo** [comment]
oops, you should return `Observable<Mutation>` in `catchError` closure.

```swift
.catchError { Observable.just(Mutation.setError($0)) }
```
