### ISSUE TITLE
Automated tasks & transitioning UI between states

### ISSUE THREAD

**Issue by zdenektopic** [ReactorKit/ReactorKit#15]
Lets imagine you have some application that requires synchronisation. This synchronisation is ran every time a user opens the app (becomes active). How does this fit to ReactorKit, where this should be implemented?

When sync completes, it usually changes UI in terms of adding/removing items from table view etc. so eventually it has to somehow update the State of one or more Reactors.

This brings me to another thing with transitioning between states - like add rows to UITable/CollectionView, animating changes etc. How this should be done using ReactorKt if there is some best practice for this or a guideline.

**Comment by devxoul** [comment]
Global state management is not a ReactorKit's responsibility. So you can use anything to manage the synchronisation. For example, you can use a global `Subject` to store synchronisation process or you can even use `Reactor` as a global synchronisation state manager. The important thing is that a Reactor can observe the global state and update its state.

Let's assume that we have a sync state as a `Variable`.

```swift
// global scope
struct SynchronisationState {
  var usernames: [String] // example properties that will be binded to table view
}
let syncState = Variable<SynchronisationState>(SynchronisationState(usernames: []))

// AppDelegate.swift
func applicationDidBecomeActive(_ application: UIApplication) {
  Synchroniser.sync() { newState in
    syncState.value = newState // emit a synchronised state
  }
}

// MyViewReactor.swift
class MyViewReactor: Reactor {
  enum Action { ... }
  enum Mutation {
    case setUsernames(String)
  }
  struct State {
    var usernames: [String]
  }

  // Merges two observables into a single observabe:
  //   1. Mutation observable from Reactor
  //   2. Mutation observable from global `syncState`
  func transform(mutation: Observable<Mutation>) -> Observable<Mutation> {
    let fromSyncState = syncState.asObservable()
      .map { $0.usernames }
      .map { Mutation.setUsernames($0) }
    return Observable.merge(mutation, fromSyncState)
  }

  func reduce(state: State, mutation: Mutation) -> State {
    switch mutation {
    case let .setUsernames(usernames):
      var newState = state
      newState.usernames = usernames
      return newState
    }
  }
}
```

**Comment by zdenektopic** [comment]
I see. So I should also transform and map the data as they are supposed to go to view? Does Reactor also poses as `ViewModel` then?

What about transitioning between data? Like `UITableView`s `beginUpdate`, `insertRows` etc?

**Comment by devxoul** [comment]
@zdenektopic, You can directly map the global state to the View but it's recommended to use Reactor for testability. It's true that a Reactor it similar to a ViewModel because ReactorKit was originally started from MVVM.

If you're using [RxDataSources](https://github.com/RxSwiftCommunity/RxDataSources) you just can use `RxTableViewSectionedAnimatedDataSource` or `RxCollectionViewSectionedAnimatedDataSource` for animated updates. Otherwise you can use `beginUpdate()` and `endUpdate()`.

**Comment by zdenektopic** [comment]
Ok.

What I feel when looking at ReactorKit is that I am somehow missing the ViewModel. Reactor as by name already reminds of something that is yet behind the view model and controls all the tasks like networks requests/services etc.

**Comment by devxoul** [comment]
Please reopen it if you have further questions :)

**Comment by PierreBrisorgueil** [comment]
Hey, first of all thank you for the work. New on swift I test many solutions.

I will ask a question to complete the example above and check my understanding.

could you add an example of a second view reactor inserting a String into the usernames array for example? that will update the global state with an addusername mutation
