### ISSUE TITLE
One action create multi mutation

### ISSUE THREAD

**Issue by kaich** [ReactorKit/ReactorKit#156]
I want to requet the class info. There are two request. A for class basic information. B for class students information.  First I send a A request.  When A request complete, use the response to send B request.  But I want change state to refresh UI when A request complete.  How to do ?

A  -> A Response -> Change State ->  B ->  B Response -> Change State.

```
    func mutate(action: Action) -> Observable<Mutation> {
        switch action {
        case A:
            ARequest.map {Mutation.setClassInfo($0)}
        }
    }
```

One Action Only Return One Mutation. I don't how to send B request .  I don't how to write the code. 
Please help me. Thanks

**Comment by tokijh** [comment]
Hou about use `Observable.concat()`

```swift
func mutate(action: Action) -> Observable<Mutation> {
  switch action {
    case A:
      return Observable.concat([
        ARequest.map { Mutation.setClassInfo($0) },
        BRequest.map { Mutation.setStudentsInfo($0) },
      ])
  }
}
```

BRequest will starts after when ARequest is completed

Also you can use other operations like `Observable.zip()` and `Observable.merge()` for your situations!

**Comment by kaich** [comment]
@tokijh  Thanks for your reply. But there are something I forgot to say. B requests params depend on A Response. How to write the code ?

**Comment by tokijh** [comment]
@kaich Try this!

```swift
func mutate(action: Action) -> Observable<Mutation> {
  switch action {
    case A:
      return ARequest.flatMap { classInfo in
        return Observable.merge(
          Observable.just(Mutation.setClassInfo(classInfo)),
          BRequest.request(with: classInfo).map { Mutation.setStudentsInfo($0) }
        )
      }
  }
}
```

Use another operators instead of `Observalbe.merge()` according to the situation.

**Comment by kaich** [comment]
@tokijh That's so good! Thanks very much.
