### ISSUE TITLE
How to cancel the request in Reactor, when it haved popViewController

### ISSUE THREAD

**Issue by tospery** [ReactorKit/ReactorKit#159]
![image](https://user-images.githubusercontent.com/3716286/87868921-9136fc80-c9cd-11ea-8af7-25a82f0b6e6f.png)
    func mutate(action: Action) -> Observable<Mutation> {
        switch action {
        case .login:
            return .concat([
                .just(.setError(nil)),
                self.provider.login(username: "myAccout", userid: "abc", password: "password")
                    .map { _ in Mutation.setStatus(.installed) }
            ])
Note: How can i cancel the login request, when i haved pop this reactor's viewController?

**Comment by kaich** [comment]
I think it's not belong to the Reactorkit. You can refer to the https://stackoverflow.com/questions/49271118/rxalamofire-cancel-network-request

**Comment by asapo** [comment]
You can cancel it by using `takeUntil()` operator.

Please read this example.
https://github.com/ReactorKit/ReactorKit/blob/2592a48d275d7aaba4660a195cd99c0a62df6833/Examples/GitHubSearch/GitHubSearch/GitHubSearchViewReactor.swift#L45

> when i haved pop this reactor's viewController?

You can fire an action for cancellation from view controller. Eg, viewWillDisappear, viewDidDisappear

**Comment by tokijh** [comment]
```swift
enum Action {
  case login
  case cancelLogin
}

func mutate(action: Observable<Action>) -> Observable<Mutation> {
  switch action {
  case .login:
    return self.provider.login(...)
      .takeUntil(self.action.filter(self.isCancelLogin))
  }
}

private func isCancelLogin(_ action: Action) -> Bool {
  guard case .cancelLogin = action else { return false }
  return true
}
```

**Comment by tospery** [comment]
thanks
