### ISSUE TITLE
I don't want some action to change state

### ISSUE THREAD

**Issue by kaich** [ReactorKit/ReactorKit#160]
When I click a button, I send `self.reactor?.action.onNext(.aAction)`. But I don't this action to change the state and force UI refresh.  Are there any way to do it ?

**Comment by asapo** [comment]
It is depends on what you want.

Maybe, to do that, you can use `Observable.empty()` to avoid any `Mutation`.

```swift
Observable.just(1).flatMap { Observable<Mutation>.empty() }

Observable.just(1).ignoreElements().andThen(Observable<Mutation>.empty())
```

**Comment by kaich** [comment]
@asapo  that's so good. thanks very much.
