### ISSUE TITLE
How can i cancel the prev action's async task?

### ISSUE THREAD

**Issue by tospery** [ReactorKit/ReactorKit#161]
![image](https://user-images.githubusercontent.com/3716286/89811699-9c66ed80-db71-11ea-9f0d-be01e0b6bd47.png)
![image](https://user-images.githubusercontent.com/3716286/89811781-be607000-db71-11ea-92d7-2c7c31264a62.png)
![image](https://user-images.githubusercontent.com/3716286/89811951-f9fb3a00-db71-11ea-803d-98765c54e7de.png)
![image](https://user-images.githubusercontent.com/3716286/89812224-62e2b200-db72-11ea-940e-255b145b9a95.png)
Thanks

**Comment by asapo** [comment]
How about `takeUntil` operator?
https://github.com/ReactorKit/ReactorKit/blob/573d7a7a114a5b3188eb1201ae5fe47eecc935c9/Documentation/Tutorials/GitHubSearch/4-ImplementingReactor.md

**Comment by tospery** [comment]
> How about `takeUntil` operator?
> https://github.com/ReactorKit/ReactorKit/blob/573d7a7a114a5b3188eb1201ae5fe47eecc935c9/Documentation/Tutorials/GitHubSearch/4-ImplementingReactor.md

thanks asapo

**Comment by yermukhanbet** [comment]
@tospery Did your setLoading function worked fine after adding takeUntil?
