### ISSUE TITLE
Carthage: no shared scheme

### ISSUE THREAD

**Issue by zdenektopic** [ReactorKit/ReactorKit#17]
Hi,

currently it is not possible to install ReactorKit using Carthage.
```
*** Skipped building ReactorKit due to the error:
Dependency "ReactorKit" has no shared framework schemes for any of the platforms: iOS
```

**Comment by devxoul** [comment]
I don't want to include .xcodeproj file on the Git repository so I just created a PR on Carthage: https://github.com/Carthage/Carthage/pull/1945 I'll add a xcodeproj file if this PR takes too long to be merged :)

**Comment by zdenektopic** [comment]
this might take a while

**Comment by devxoul** [comment]
Yeah. I need some several setup for this. I'll do this in next 6 hours :)

**Comment by devxoul** [comment]
There were too many issues on generating xcodeproj with dependencies. I think it's better to upload prebuilt binary instead. Travis CI takes too long to test so I'll check this again tomorrow.

**Comment by ufosky** [comment]
The prebuilt binary depend on RxCocoaRuntime.framework, but I can't find it.

**Comment by zdenektopic** [comment]
Thats weird. I never linked `RxCocoaRuntime` into my projects.

**Comment by devxoul** [comment]
@ufosky, I don't know why Carthage creates RxCocoaRuntime when I add RxSwift dependency with ReactorKit, but not creates when I add only ReactorKit.

**Comment by ufosky** [comment]
This is an output at runtime:
```
dyld: Library not loaded: @rpath/RxCocoaRuntime.framework/RxCocoaRuntime
  Referenced from: /private/var/containers/Bundle/Application/CBF1F46A-5775-47EC-AD7C-C3F1327D6483/******.app/Frameworks/ReactorKit.framework/ReactorKit
  Reason: image not found
```
The `Cartfile.resolved` file content:
```
github "Alamofire/Alamofire" "4.4.0"
github "Hearst-DD/ObjectMapper" "2.2.7"
github "Moya/Moya" "8.0.5"
github "ReactiveCocoa/ReactiveSwift" "1.1.3"
github "ReactiveX/RxSwift" "3.5.0"
github "ReactorKit/ReactorKit" "0.4.4"
github "RxSwiftCommunity/RxDataSources" "1.0.3"
github "SwiftKickMobile/SwiftMessages" "3.3.3"
github "SwiftyBeaver/SwiftyBeaver" "1.2.2"
github "adamwaite/Validator" "v2.1.1"
github "antitypical/Result" "3.2.3"
github "devxoul/RxViewController" "0.1.0"
```

**Comment by devxoul** [comment]
@ufosky, can you see `RxCocoaRuntime.framework` in `./Carthage/Build/iOS` directory?

**Comment by ufosky** [comment]
No, but I can see `RxCocoa.framework` .

**Comment by devxoul** [comment]
Hmm, this is weird. Let me check it out.

**Comment by devxoul** [comment]
@zdenektopic @ufosky I think I have succeeded!!!!! https://github.com/ReactorKit/ReactorKit/releases/tag/0.4.5

**Comment by ufosky** [comment]
There is another issue when I upload my App to iTunes.

```
ERROR ITMS-90056: "This bundle Payload/***.app/Frameworks/ReactorKit.framework is invalid. The Info.plist file is missing the required key: CFBundleVersion."
```

**Comment by ufosky** [comment]
I also see the MinimumOSVersion is 10.3 in the info.plist.

**Comment by zdenektopic** [comment]
Same here

**Comment by devxoul** [comment]
@ufosky @zdenektopic Could you try again with 0.4.5?

**Comment by ufosky** [comment]
Prebuilt binary not compatiable for xcode 9 beta，which is use swift 4.

**Comment by devxoul** [comment]
@ufosky does it work with Swift 3 in Xcode 8?

**Comment by ufosky** [comment]
@devxoul  Yes.

**Comment by devxoul** [comment]
That's good to hear. I'll update the prebuilt binary to Swift 4 in this week :)

**Comment by zdenektopic** [comment]
Why? It is prerelease. We wont be able to use it in our projects.

**Comment by devxoul** [comment]
@zdenektopic yeah, I just checked the developer site and it seems that Xcode 9 is currently in beta. @ufosky I'll update the Swift version after the Xcode 9 release :)

**Comment by devxoul** [comment]
Well, I think I can close this issue now. Please reopen it if you face the same problem again.

**Comment by zdenektopic** [comment]
Actually I believe we would appreciate carthage buildable without needed to download prebuilt binary. The reason is the new Xcode, we can easily build all carthage modules with Xcode9 and Swift 3.2. This is way a I cannot do it because ReactorKit is the only one that doesnt provide shared scheme in our project :(

**Comment by devxoul** [comment]
It's not that easy to provide a Xcode project because ReactorKit has a RxSwift dependency. If the project has a dependency to other libraries, a SPM generated Xcode project is not compatible with the Carthage. This is why I provide the prebuilt binary rather than the project file. I'll try to find another solution for this.

**Comment by zdenektopic** [comment]
well, it is fairly small project so I believe you can just keep Xcode project updated manually no?

**Comment by zdenektopic** [comment]
Any update on this? Xcode 9 b3 is usable already, so it would be nice to be able to build ReactorKit with Carthage

**Comment by devxoul** [comment]
@zdenektopic, Unfortunately :(
