### ISSUE TITLE
How to handle global state?

### ISSUE THREAD

**Issue by tomisacat** [ReactorKit/ReactorKit#181]
In `Redux`, there is only one Store and many sub-reducers/states/actions, and the action and state will flow into specific reducer, you could handle global state through the only Store. But for `Reactorkit`, View/StoryboardView is binded to its corresponding Reactor, is there a good place to put/subscribe the global state(eg. Logged in user)?

**Comment by JuyeonYu** [comment]
for the global state, you can make subject or reactor in public.
and in your reactor which needs the global state, call 'transform(mutation: ' function.

in detail you'd better to check this.
https://github.com/ReactorKit/ReactorKit#global-states

**Comment by tomisacat** [comment]
@JuyeonYu Thanks for your reply!
