### ISSUE TITLE
Showing errors and updating input fields

### ISSUE THREAD

**Issue by zdenektopic** [ReactorKit/ReactorKit#20]
Is there any best practice, recommendation, a guideline on how to display error that occurred in `Mutation` `Observable`?

Eg 1: I am fetching data from web service and I get my auth token expired error so I need to somehow present this in UI.

Eg 2: I have some UITextField. On some action, that gets called I will want the mutation to update the text in this field. How is this achieved?

Thanks!

**Comment by devxoul** [comment]
**Eg 1**

You may add a error information to a state.

```swift
enum Mutation {
  case setData(SomeData)
  case setFetchingDataError(Error?)
}

struct State {
  var data: SomeData
  var fetchingDataError: Error?
}

func mutate(action: Action) -> Observable<Mutation> {
  ...
  return fetchData()
    .map(Mutation.setData) // when succeeded
    .catchError { error in Observable.just(Mutation.setFetchingDataError(error)) } // when failed
  ...
}
```

Or you can abstract the data and error with `Result` model.

**Eg 2**

I'm not sure I understood your situation but I think you may want to use as following:

```swift
struct State {
  var text: String?
}

func bind(reactor: MyReactor) {
  reactor.map { $0.text }
    .distinctUntilChanged()
    .bind(to: textField.text)
    .disposed(by: disposeBag)
}
```

**Comment by zdenektopic** [comment]
Thanks. Errors I understand, however if you have UITextField and you need 2-way binding. You need to have like `username` property in your `State` and have `UITextField` updating it when text changes and update `UITextField.tex`t if some other `Mutation` changes it.

**Comment by devxoul** [comment]
Oh yeah, in this case you may use `rx.text.changed` in `View->Action` and `distinctUntilChanged()` in `State->View` to prevent from infinite loop :)

**Comment by zdenektopic** [comment]
Can you provide sample code please? :) Not sure I follow.

**Comment by devxoul** [comment]
Of course!

```swift
textField.rx.text.changed
  .map(Reactor.Action.updateUsername)
  .bind(to: reactor.action)

reactor.state.map { $0.username }
  .distinctUntilChanged()
  .bind(to: textField.rx.text)
```
