### ISSUE TITLE
View is ambiguous type. Clash between SwiftUI public protocol and ReactoriKit's public protocol.

### ISSUE THREAD

**Issue by yermukhanbet** [ReactorKit/ReactorKit#204]
Our team is using ReactorKit, and we are loving it a lot!
Currently we are working on UIKit. However, we are working right now on adding preview feature same as on SwiftUI's one.

Following this tutorial: https://www.swiftjectivec.com/using-xcode-previews-for-uikit/ 

However, as we figured out, there is a clash between public protocol 'View' from SwiftUI, and public protocol from ReactorKit 'View'

<img width="746" alt="Screen Shot 2022-04-26 at 3 44 22 PM" src="https://user-images.githubusercontent.com/46320390/165238217-7b26a411-e29f-4b2b-a198-2eaef3f4a592.png">

<img width="649" alt="Screen Shot 2022-04-26 at 3 44 50 PM" src="https://user-images.githubusercontent.com/46320390/165238293-e9fe4c3b-c021-40f2-a863-25f75abea09f.png">

Are there any workarounds this issue?
Or may be any plans for renaming public protocol 'View' ?

**Comment by tokijh** [comment]
There are no plans yet.
First, use `ReactorKit.View` and `SwiftUI.View`.
Is there a name you recommend instead of `View`?

**Comment by yermukhanbet** [comment]
@tokijh I just opened PR! Please, have a look at it and let me know your opinion.

**Comment by tokijh** [comment]
Oh, you already posted it (https://github.com/ReactorKit/ReactorKit/pull/205)
