### ISSUE TITLE
How to tell difference between 2 actions that result in same mutation

### ISSUE THREAD

**Issue by zdenektopic** [ReactorKit/ReactorKit#29]
Hello,

I am building an application that is using UITableView for displaying list of some items. There is also some other screen where you can pick a filter for those items. The problem I encountered with state is that I have an array of those items in state and I am running diff on that array whenever state changes so I can remove/insert rows from/to table view with animation. However, when I change the filter, I want to actually do this without the animation. The issue is that I do not, know how to tell when it is just items that changed for whatever reason and when the items changed because of the new filter was applied. Even if I have filter in my state struct.

Maybe my whole approach is wrong.

I have action `.subscribeToListChanges` that generates a mutation whenever something in Realm changes (it is basically never completing Observable). Then I have action `.setFilter` that sets filter. That changes filter which triggers also new mutation from `.subscribeToListChanges` Observable.

**Comment by devxoul** [comment]
I think you should add another property to the state:

```swift
struct State {
  var isFilterSetRecently: Bool // set to true on `.setFilter` and false on other actions
  var items: [Item]
}
```

**Comment by zdenektopic** [comment]
yes, I suppose that is the way. However I also think, it would be nice to have the actual mutation that was happening available so you can maybe determine you want to do some sort of animation in that case, etc
