### ISSUE TITLE
Can't set rootViewController with XIB

### ISSUE THREAD

**Issue by Sky-star** [ReactorKit/ReactorKit#31]
Hey, I import ReactorKit in my project.  when i set rootViewController it can't load xib File.Sorry about my english。

**Comment by devxoul** [comment]
@Sky-star How can I reproduce the bug?

**Comment by Sky-star** [comment]
I just create a test project, [here](https://github.com/Sky-star/ReactorKitTest.git) . 
I set the view color with pink, but when i run the project i got white.

**Comment by devxoul** [comment]
You set background color in a storyboard, but you are not using Storyboard.

<img width="504" alt="screen shot 2017-07-31 at 4 51 04 pm" src="https://user-images.githubusercontent.com/931655/28767890-7e13a1a8-7610-11e7-88e4-14df54b365a8.png">

**Comment by Sky-star** [comment]
![image](https://user-images.githubusercontent.com/6882646/28767973-7f6624d8-759b-11e7-9807-f4766a5726ca.png)
this is empty application, no Main.stroyboard in here. so I set rootViewController in AppDelegate.
i set color in RootViewController.xib.

**Comment by devxoul** [comment]
Oh, my bad. You have to initialize the view controller using `init(nibName:bundle:)` if you're using a single xib file.

```diff
- RootViewController()
+ RootViewController(nibName: "RootViewController", bundle: Bundle.main)
```

![simulator screen shot 31 jul 2017 5 21 15 pm](https://user-images.githubusercontent.com/931655/28768978-aeda8064-7614-11e7-982e-df0c85d867b7.png)

**Comment by Sky-star** [comment]
Thanks for your help~ it seems like can't support default initialization method. So Sad.
Do you know where the problem is?  Because when i remove ReactorKit in Project, it Can operate normally.

**Comment by devxoul** [comment]
Hmm yeah, it seems a ReactorKit bug. I'll check this soon. Thanks for reporting.

**Comment by Sky-star** [comment]
Thank you very much. it's nice kit.

**Comment by devxoul** [comment]
@Sky-star, #38 could fix this bug.
