### ISSUE TITLE
Async operation before reduce

### ISSUE THREAD

**Issue by kcaluru** [ReactorKit/ReactorKit#37]
Hi! I was wondering why you perform async operations before the reduce. What if the async operation requires some variable stored in your previous state. Isn't the previous state only accessible in reduce? How would I go about handling this case?

**Comment by kcaluru** [comment]
Hey, I was looking into the code and realized that you are storing state in currentState. While this solves the problem, I still don't understand why async stuff cannot happen during the reduce step.

**Comment by devxoul** [comment]
Because the state should be changed synchronously. If the state can be changed concurrently it will loose the thread safety :)

(Copied from Slack)
