### ISSUE TITLE
Triggering Action

### ISSUE THREAD

**Issue by asyl** [ReactorKit/ReactorKit#41]
Is there any chance to trigger the Action without subscribing to State?

For Example:
I have Action `saveKey(Key)`
```swift
enum Action {
  case saveKey(Key)
}
```
and I want to trigger action case without returning any `Mutation` case.

```swift
func mutate(action: Action) -> Observable<Mutation> {
  switch action {
  case let .saveKey(key):
    userService.appendKey(key)
    return .empty()
  }
}
```
Should I return `.empty()` observable? But it doesn't work

**Comment by zdenektopic** [comment]
you need to subscribe to it so it is not disposed/deallocated right away.

**Comment by asyl** [comment]
@zdenektopic you mean it needs to subscribe to Action?

**Comment by devxoul** [comment]
@asyl,

1. I didn't understand 'triggering the Action without subscribing to State'. Could you please share me some detailed situation?
2. You should always return Observable from `mutate()`. Returning `.empty()` is also my preferred way but it would be better to use like:

    ```swift
    return Observable.create { [weak self] in
      self?.userService.appendKey(key)
      return Disposables.create()
    }
    ```

**Comment by asyl** [comment]
@devxoul Thank you.

##Scenario
I used ReactorKit and realized that my actions really work when I subscribe to the State. 
For example:
I have UI components bound to some action in my `Reactor`
```swift
self.button.rx.tap
  .flatMap { self.textField.rx.text }
  .map { Reactor.Action.appendElement($0) }
  .bind(to: reactor.action)
  .disposed(by: disposeBag)
```
where `Action`:
```swift
enum Action {
  case appendElement(element)
}
```
and in `mutate(action: Action)` function, I have only one Side Effect where I save my element into the disk. But it doesn't work. Even break points don't work unless I create `Mutation` and `State` for this case and I subscribe to the `State` in my `View`, like this:
```swift
reactor.state.map { $0.element }
  .subscribe { print($0) }
  .disposed(by: disposeBag)
```
After all of that, I can see how break points stop in `mutate(action: Action)` and function works.

##Question
How I can bind my UI components to`Action` without creating any `Mutation` & `State`?

**Comment by devxoul** [comment]
Ah, I got it. You may want to create a state stream without binding it to the view. Try this:

```swift
class MyReactor {
  init(params: MyParameters) {
    self.initialState = State(foo: bar)
    _ = self.state // add this line to create a state immediately
  }
}
```
