### ISSUE TITLE
Build Xcode9 with Carthage

### ISSUE THREAD

**Issue by ppth0608** [ReactorKit/ReactorKit#44]
Hi there~

I'm using ReactorKit from Carthage.

When build with Xcode9, there are error because ReactorKit compiled with 3.1

So, I try to rebuild framework using `carthage update --no-use-binaries` then,
terminal say `Dependency "ReactorKit" has no shared framework schemes`

**Comment by devxoul** [comment]
Which error did you get with Swift 3.1 in Xcode 9?

**Comment by ppth0608** [comment]
As far as I know, Xcode9 supports Swift3.2(which are compatible versions) and Swift4. If you build Carthage pre-build framework with Swift 3.2, it seems to be solved.

**Comment by devxoul** [comment]
ReactorKit support Swift 4 since [1.0.0 release](https://github.com/ReactorKit/ReactorKit/releases/tag/1.0.0).
