### ISSUE TITLE
Service layer?

### ISSUE THREAD

**Issue by mheras** [ReactorKit/ReactorKit#51]
Hi,

The documentation states that ReactorKit has a special Service layer to do every heavy or asynchronous operation, but I cannot find the Service protocol/class in the source code.

Is it something that was removed from code but not from the documentation?

Thanks,
M

**Comment by devxoul** [comment]
@mheras, thanks for asking. A service layer is just an abstract concept of how to do a business logic. Yeah the documentation seems confusing. I'll update it with more explicit words :)

**Comment by mheras** [comment]
@devxoul Ok, got it! Thank you!
