### ISSUE TITLE
ReactorKit Ignore initial action..

### ISSUE THREAD

**Issue by makesource** [ReactorKit/ReactorKit#54]
Hi, I'm developing a tableView with UISegmentedControl using ReactorKit .. and I found some problems in ReactorKit.

 As far as I understand, the Reactor does not trigger mutate(), reduce() until state stream subscribed. That's why we have to do binding state explicitly to trigger action.(https://github.com/ReactorKit/ReactorKit/issues/41)
It's not a big problem in many cases, but when I use UIViews which have initial state (such as UISegmentedControl), I face some problem.
As mutate() does not being called until state subscribed (or binded), If we bind actions before state subscribed (as docs example does) it can disregard initial action of UIView.

So below snippet does not work as I intended, the second one worked perfectly for me.

First Version
```
// Action   
segmentedControl.rx.value
            .map(Reactor.Action.setSortType)
            .bind(to: reactor.action)
            .disposed(by: disposeBag)

// State
 reactor.state
            .asObservable()
            .map { $0.comments }
            .map { [SectionModel(model: "comments", items: $0)] }
            .bind(to: tableView.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)
```

Second Version
```
// State
 reactor.state
            .asObservable()
            .map { $0.comments }
            .map { [SectionModel(model: "comments", items: $0)] }
            .bind(to: tableView.rx.items(dataSource: dataSource))
            .disposed(by: disposeBag)

// Action   
segmentedControl.rx.value
            .map(Reactor.Action.setSortType)
            .bind(to: reactor.action)
            .disposed(by: disposeBag)
```

So I think it's safe to restrict bind ordering (State binding -> Action binding)
Or subscribe state explicitly when declear state stream

**Comment by devxoul** [comment]
As I described in https://github.com/ReactorKit/ReactorKit/issues/41#issuecomment-325453152, it is recommended to add `_ = self.state` to create a state stream immediately.

> ```swift
> class MyReactor {
>   init(params: MyParameters) {
>     self.initialState = State(foo: bar)
>     _ = self.state // add this line to create a state immediately
>   }
> }
> ```

Or, if you use [ReactorKit 1.1.0](https://github.com/ReactorKit/ReactorKit/releases/tag/1.1.0) it will automatically create a state stream when you first access to an `action`.
