### ISSUE TITLE
StoryboardView 프로토콜을 사용하였을 때, rx.viewDidLoad 이벤트를 받을 수 없습니다.

### ISSUE THREAD

**Issue by heyjerks** [ReactorKit/ReactorKit#55]
안녕하세요.

StoryboardView 프로토콜을 사용하였을 때, bind(reactor:) 함수에서
rx.viewDidLoad 이벤트를 받을 수 없습니다.

확인한 바로는 ReactorKitRuntime에서 viewDidLoad를 swizzle 하여
viewDidLoad가 호출 된 이후에 bind(reactor:)가 호출되기 때문인 것으로 확인됩니다.

viewDidLoad가 아닌 loadView 함수와 swizzle 하면 수정이 될 것으로 판단됩니다.

확인 부탁드립니다.

**Comment by devxoul** [comment]
In most case people initialize their custom views in `viewDidLoad()`. It will be the breaking change if we swizzle `loadView()`. I'd recommend you to not use `rx.viewDidLoad` with `StoryboardView`. You may use `Observable.just` alternatively:

```diff
  func bind(reactor: MyReactor) {
-    self.rx.viewDidLoad
+    Observable.just(Void())
      .map { Reactor.Action.foo }
      .bind(to: reactor.action)
  }
```

PS: This repository is not only for Korean. Please respect others.

**Comment by heyjerks** [comment]
I understood what you mean. I'm sorry to have registered issue in Korean.
