### ISSUE TITLE
Carthage build error

### ISSUE THREAD

**Issue by mheras** [ReactorKit/ReactorKit#59]
Hi,

When compiling with Carthage, I get the following error:

![image](https://user-images.githubusercontent.com/323266/35952053-ea4562ca-0c5c-11e8-99f7-55743c9362a4.png)

Could you please help me?

Thanks

**Comment by devxoul** [comment]
I updated the prebuilt binary. Could you try again? Thanks!

**Comment by mheras** [comment]
Fixed, thank you.
