### ISSUE TITLE
Can't transform the global state to a mutation while observing this state

### ISSUE THREAD

**Issue by vadimue** [ReactorKit/ReactorKit#60]
Hi, I want to transform the global state to a mutation. It is perfect to use 
```
func transform(mutation: Observable<Mutation>) -> Observable<Mutation> {
    return .merge(mutation, anotherMutationFromGlobalState())
}
```
But I need to use reactor's state to determinate if I really need this mutation from global state. So my code looks like 
```
  func transform(mutation: Observable<Mutation>) -> Observable<Mutation> {
    return .merge(mutation, positionMutation(mutation))
  }

  private func positionMutation(_ mutation: Observable<Mutation>) -> Observable<Mutation> {
    return mutation
      .flatMapLatest { [weak self] mutation -> Observable<CLLocation> in
        guard let `self` = self, case .autoTrackingSwitched(true) = mutation else { return .empty() }
        return self.trackingService.track()
      }
      .map(Mutation.updatePosition)
  }

```
But `.merge(mutation, positionMutation(mutation))` breaks action-mutation-state flow, because it emits double mutation instead of one, so all my actions duplicated. Сan I transform mutation in Reactor with observing Reactor state(or mutation)? For better understanding my business logic: I have the UISwitch in UIViewController and I want to get locations from service with protocol `func track() -> Observable<CLLocation>` when UISwitch is On and want to dispose this observable when the UISwitch is Off.

**Comment by devxoul** [comment]
I think there are many cases. It depends on how `trackingService` works.

1. If the TrackingService always tracks the user location and there's no interface for enabling or disabling it:

    You may filter the observation values.

    ```swift
    func transform(mutation: Observable<Mutation>) -> Observable<Mutation> {
      return .merge(mutation, positionMutation())
    }

    private func positionMutation() -> Observable<Mutation> {
      self.trackingService.track()
        .filter { [weak self] _ in self?.currentState.isOn == true }
        .map(Mutation.updatePosition)
    }
    ```

2. If the TrackingService provides an interface for enabling or disabling:

    You should separate the on/off operation and the location observing operation. Just keep observing the `track()` whether it emits value or not. And enable or disable the service when the reactor receives a mutation.

    ```swift
    func transform(mutation: Observable<Mutation>) -> Observable<Mutation> {
      return .merge(autoTrackingSwitchingMutation(mutation), positionMutation())
    }

    func autoTrackingSwitchingMutation(_ mutation: Observable<Mutation>) -> Observable<Mutation> {
      guard case let .autoTrackingSwitched(isOn) = mutation else { return mutation }
      return mutation.do(onNext: { [weak self] _ in
        self?.trackingService.setEnabled(isOn)
      })
    }

    private func positionMutation() -> Observable<Mutation> {
      return self.trackingService.track().map(Mutation.updatePosition)
    }
    ```

**Comment by vadimue** [comment]
@devxoul, Thanks for the answer.
I fix this issue through separate service, which saves `UISwitch` state. Reactor updates the state, `trackingService` use that state in `flatMap()` operator. I need to unsubscribe from `trackingService`, because it stops updates from `CLLocationManager`.
