### ISSUE TITLE
The state in transform(state: Observable<State>) is different than the current state

### ISSUE THREAD

**Issue by lowip** [ReactorKit/ReactorKit#68]
I am unsure that this is an issue or just me not understanding how state transformation works.

When using `transform(state: Observable<State>) -> Observable<State>`, previous transformations are not available in the parameter state.

For instance:
```swift
struct State {
  var flag = false
  var counter = 0
}

func transform(state: Observable<State>) -> Observable<State> {
  return state.map { state in
    var state = state
    state.counter += 1
    return state
  }
}
```

If the variable `counter` is not modified elsewhere (by a mutation for instance), it will always be equal to `1`.

In the view:
```swift
function bind(reactor: MyReactor) {
  // Counter should count the number of state changes
  reactor.state.map { $0.counter }
    .bind {
      print($0) // Always prints 1
    }
    .disposed(by: self.disposeBag)

  // Perform some actions which mutate state.flag
  reactor.action.onNext(.setFlag(true))
  reactor.action.onNext(.setFlag(false))
  reactor.action.onNext(.setFlag(true))
  reactor.action.onNext(.setFlag(false))
}
```

I couldn't find any documentation regarding this point, so this might be how it is supposed to behave but I am unsure.

**Comment by devxoul** [comment]
`transform(state:)` doesn't manipulate the state stream. This transformation only affects to a view and `currentState` at the very end of the state delivery cycle. This is intended behavior to keep `reduce()` only way to manipulate the state.

**Comment by lowip** [comment]
Thanks for the precisions!
I'll close the issue.
