### ISSUE TITLE
Repeated action every x second

### ISSUE THREAD

**Issue by GizmoJon** [ReactorKit/ReactorKit#70]
Good day guys,

Trying to figure out how could I achieve an action every 20s (like you would by using a NSTimer.scheduledTimerWithTimeInterval call).

Essentially on startup I would like to make startWith the Action.fetchSomething and schedule that action every 20s. 

I have troubles figuring out how I could achieve this.

Thank you in advance

**Comment by devxoul** [comment]
I would use mutation instead. For example:

```swift
enum Mutation {
  case setFetchResult(MyFetchResult)
}

func mutate(action: Action) -> Observable<Mutation> {
  switch action {
  case .startFetchSomething:
    return Observable.interval(20, scheduler: myScheduler)
      .flatMap { API.fetchSomething() }
      .map { Mutation.MyFetchResult($0) }
  }
}
```

**Comment by GizmoJon** [comment]
Thank you! @devxoul
