### ISSUE TITLE
Is there any ways to prevent the fat bind function?

### ISSUE THREAD

**Issue by kou0117** [ReactorKit/ReactorKit#72]
I have a question.
When using Reactorkit, I sometimes have the fat bind function which has more than 100 lines.

Even I do not know whether it is good or bad, but if you have any idea to prevent this, please let me know.

**Comment by sgtsquiggs** [comment]
@kou0117 My bind function calls several other bind functions. For instance, I have bindActions which are view->reactor, then I have bindState which binds reactor->view.

You could also move your binding code into reactive extensions on your view, so all of the logic exists in the extension and your bind(reactor) method is just connecting the dots.

**Comment by kou0117** [comment]
@sgtsquiggs 
Thank you for your reply and I would do your ways.
