### ISSUE TITLE
How about avoiding `self` usage

### ISSUE THREAD

**Issue by cruisediary** [ReactorKit/ReactorKit#86]
#### Relying on a compiler bug

There is a bug in current versions of the Swift compiler that allow self to be assigned when the word is surrounded by backticks.

This bug causes the following code to compile and work:

```swift
guard let `self` = self else {
    return
}
```
Apple’s Chris Lattner has stated that “this is a compiler bug”.

Therefore, we should not rely on this “feature” to work in the future, because the bug will (presumably) be fixed eventually.

[Swift-evolution](https://lists.swift.org/pipermail/swift-evolution/Week-of-Mon-20160118/007425.html)
> To confirm what others have said down thread, this is a compiler bug: this code is valid, but shouldn’t change what references to “self.method()” or “method()" bind to (i.e., explicit or implicit references to self).
Backquotes are for forming a name that happens to overlap with a keyword.  In the case of `self`, this could be because you want to refer to the NSObject.`self` method for some reason.  Backquotes are not a way to name self, init, subscript or any of the other declarations that look like magic identifiers.

**Comment by devxoul** [comment]
In Swift 4.2 [this proposal](https://github.com/apple/swift-evolution/blob/master/proposals/0079-upgrade-self-from-weak-to-strong.md) has been implemented so this is no more a compiler bug but a feature :)
