### ISSUE TITLE
[Question] How to use "state" of custom class or error

### ISSUE THREAD

**Issue by touyu** [ReactorKit/ReactorKit#88]
Hi, I have a question "How to use state of custom class or error"

For example, 
```swift
class User {
    var name: String
}

class SampleViewReactor: Reactor {
    struct State {
        var user: User
        var error: Error
    }
}

class SampleViewController: UIViewController, View {
    func bind(reactor: Reactor) {
        reactor.state.map { $0.user }
              .distinctUntilChanged // Must I make the user `Equtable`?

        reactor.state.map { $0.error }
              .distinctUntilChanged // Must I make the error `Equtable`?
    }
}
```

What is the best solution as a means to not be called more than once?
Could you help me?

**Comment by smajdalf** [comment]
Hi @touyu, my approach of this is, like you already said, using the Equatable protocol. Swift 4.1 brings **Synthesized Equatable and Hashable**. It means, that you dont have to write your own Equatable and Hashable implementation. All you have to do is comform your type [_User_, _Error_] to Equatable protocol and Swift will do the rest. More [here](https://www.hackingwithswift.com/articles/50/whats-new-in-swift-4-1).

You will end with this:

```swift
func bind(reactor: Reactor) {
     reactor.state.map { $0.user }
           .distinctUntilChanged()

     reactor.state.map { $0.error }
           .distinctUntilChanged()
}
```

**Comment by touyu** [comment]
@smajdalf Thank you for answering!
