### ISSUE TITLE
Combined reducers?

### ISSUE THREAD

**Issue by seivan** [ReactorKit/ReactorKit#9]
Should introduce a way to make a global application store that can combine multiple reducers.
This helps if you want to dispatch actions that are captured in a middleware for logging purposes and have application wide subscriptions on the store. 

As of now, I see this for being a per viewmodel basis, but there is nothing preventing one to use a *store* for the entire application as well to keep content and state. 

Do you see any way to get a Redux like behaviour here?

**Comment by devxoul** [comment]
Thanks for asking :) Redux has global main store but ReactorKit doesn't. Global main store requires the whole application to follow the single architecture (Redux) but ReactorKit can be partially adopted to specific view. The main purpose of a reactor is to separate the business logic from a view, so there's is nothing like Redux-style-store at this time.

**Comment by devxoul** [comment]
Oh, your question was "Don't you think there should be something for preventing from using a Reactor as redux-style?" If I understood your question correctly, I think people can use ReactorKit as they want. My recommendation is to make view has its corresponding reactor but it's just a recommendation :)

**Comment by seivan** [comment]
Not preventing! But actually helping. Most applications are a combination of local and global state. 
This tackles local state to components, but there's some missing for managing a large application wide state.

**Comment by devxoul** [comment]
ReactorKit is not a Redux. Redux manages every state with `State` but ReactorKit doesn't. ReactorKit lets users to manage global state as they want and just provides a way to combine those local and global state: [`transform()`](https://github.com/ReactorKit/ReactorKit#transform).

[This example](https://github.com/devxoul/RxTodo/blob/9ece6f7a11825a4b3dabf006b78afb0e9ecb036d/RxTodo/Sources/ViewControllers/TaskListViewReactor.swift#L83-L89) merges the local `Action` and global `TaskEvent` stream and generates `Mutation`.
