### ISSUE TITLE
Communication between viewcontrollers

### ISSUE THREAD

**Issue by wpcfan** [ReactorKit/ReactorKit#94]
Hi, I played with this framework a little while, and it is great. But I still got confused about the communication between viewcontrollers. In the doc, it says something about view communication, but not viewcontrollers. Is it possible to share states or receive actions from other reactor? or I have to use a global subject to to do this?

**Comment by devxoul** [comment]
In ReactorKit a view controller is treated as a view. You may do as same as the view communications :)

**Comment by wpcfan** [comment]
Got it, thanks, closing the issue
